### ISSUE TITLE
Undefined index error on capture

### ISSUE THREAD

**Issue by mattiteraslahti** [maksuturva/magento2_payment_module#1]
**Steps to reproduce**
1. Create a new order in the store frontend and go through the payment, return to the store
2. Go to the Magento backend / order management
3. Find and open the order that was just created
4. Go to Invoices tab

**Actual result**
There's no invoice and the order is in "processing" status. There's no updates in order status history section.

**Expected result**
There's an invoice and the order is in the status that has been configured for the paid order. The order status history has information about the successful payment.

**Notes**
In \Piimega\Maksuturva\Model\Payment::capture method replace $payment->getAdditionalData() by $payment->getAdditionalInformation(). The preselected payment method is stored in additional_information column instead of additional_data.
Also add a check for undefined index.

**Comment by Svea-Maintainer** [comment]
Lots of changes to invoices since then
