### ISSUE TITLE
Exception "Deprecated Functionality: preg_replace(): Passing null to parameter" in Svea\MaksuturvaCollated\Model\Collated

### ISSUE THREAD

**Issue by oskar-olaussen** [maksuturva/magento2_payment_module#61]
The expection 
`Exception #0 (Exception): Deprecated Functionality: preg_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /var/www/html/app/code/Svea/MaksuturvaCollated/Model/Collated.php on line 58`
is thrown if there is a payment method where the "_method_filter" config is set to null.

**Comment by Svea-Maintainer** [comment]
Thank you for your contribution. We will add proper variable checks to get rid of this exception message. Code will be available in the master branch soon after testing, and part of next release version.
